### ISSUE TITLE
No-DASH video option limited by resolution

### ISSUE THREAD

**Issue by mrfuggy** [trizen/straw-viewer#22]
I launched the application with the option _--no-dash_. It allows me to use my preferences or seek to time in VLC player. I have set _resolution="1080p"_ in config.
Any video that I play opens in 720p resolution. _itag=22_ To my surprise in mp4 format. I see in the source code _itag=46_ is available with webm format.
I would like to play video in 1080p and with _--no-dash_ option. Is this a technical limitation by Youtube or by straw-viewer?

**Comment by trizen** [comment]
Due to historical reasons (mostly due to my misunderstanding at that time), `dash` in straw-viewer means videos that are split into audio+video, where `audio` and `video` are provided by two different URLs.

The highest resolution for videos with audio+video in the same file, is 720p.

The true [DASH](https://en.wikipedia.org/wiki/Dynamic_Adaptive_Streaming_over_HTTP) option can be controlled by the config-option: `dash_segmented`.
